% main_hardware_walk_fennec.m
% Real-time synchronization of two front legs tracking a custom biological trajectory.

clear; clc; close all;

%% 1. Setup Kinematics Parameters & Dimensions
Ts = 0.02;          % Sample time (50 Hz) 
T_end = 10;         % Execution duration (10 seconds of walking)
t = 0:Ts:T_end;     % Time vector

params = struct();
params.dm.L2 = 100.00; 
params.dm.L3 = 105.73; 

% Provide the name of the CSV file generated by your Fennec script
ANIMAL_CSV = 'fennec_FINAL_EDITED_foot_cycle.csv';

if ~isfile(ANIMAL_CSV)
    error(['Cannot find ' ANIMAL_CSV '. Please run the Fennec trajectory smoothing script first!']);
end

%% 2. Setup Combined Hardware Parameters
hw_params = struct();
hw_params.DEVICENAME = 'COM5';          % Check your COM port
hw_params.BAUDRATE = 1000000;           
hw_params.PROTOCOL_VERSION = 2.0;       

% --- UPDATE THESE IDs TO MATCH YOUR PHYSICAL SETUP ---
% [Right Thigh, Right Crank, Left Thigh, Left Crank]
hw_params.DXL_IDS = [4, 3, 2, 1];     

% Directions and Offsets combined for all 4 motors
hw_params.DIRECTIONS = [1, 1, -1, -1]; 
hw_params.OFFSETS = [deg2rad(0), deg2rad(143), deg2rad(360), deg2rad(324)];

%% 3. Generate Synchronized BIOLOGICAL Trajectories
% The workspace bounds remain mathematically identical to your cycloid
Xc = 40;     
Yc = -145;   
A = 20;      % Half-width (Total Stride = 40mm)
B = 15;      % Half-height (Total Step clearance = 30mm)
freq = 0.5;  
T_cycle = 1 / freq;

% Phase Shift: Right starts at 0, Left starts halfway through the cycle
t_c_right = mod(t, T_cycle);
t_c_left  = mod(t + (T_cycle / 2), T_cycle); 

disp('Reading and mapping biological data to robot workspace...');
[ref_x_R, ref_y_R] = generate_animal_trajectory(t_c_right, T_cycle, Xc, Yc, A, B, ANIMAL_CSV);
[ref_x_L, ref_y_L] = generate_animal_trajectory(t_c_left,  T_cycle, Xc, Yc, A, B, ANIMAL_CSV);

ref_pos_R = [ref_x_R; ref_y_R];
ref_pos_L = [ref_x_L; ref_y_L];

%% 4. Initialize Subsystems
% Create TWO independent controllers
ctrl_R = control.OpenLoopControl(Ts, params);
ctrl_L = control.OpenLoopControl(Ts, params);

% Calculate initial positions
init_q_R = kinematics.inverse_kinematics(ref_pos_R(:, 1), params);
init_q_L = kinematics.inverse_kinematics(ref_pos_L(:, 1), params);

if any(isnan(init_q_R)) || any(isnan(init_q_L))
    error('WORKSPACE ERROR: The biological trajectory pushes the leg out of reach. Reduce A or B.');
end

ctrl_R.PreviousAction = init_q_R;
ctrl_L.PreviousAction = init_q_L;

% Initialize Hardware
disp('Initializing hardware connection...');
hw_interface = hardware.DynamixelInterface(hw_params);
hw_interface.init();

% Map initial kinematics to hardware space
init_hw_R = (init_q_R .* hw_params.DIRECTIONS(1:2)') + hw_params.OFFSETS(1:2)';
init_hw_L = (init_q_L .* hw_params.DIRECTIONS(3:4)') + hw_params.OFFSETS(3:4)';

disp('Moving to synchronized start positions. Please stand clear...');
hw_interface.writePosition(hw_params.DXL_IDS, [init_hw_R; init_hw_L]);
pause(2.0); 

%% 5. Preallocate Logging
N = length(t);
actual_pos_R_log = zeros(2, N); 
actual_pos_L_log = zeros(2, N); 

disp('System Hot! Starting dual-leg biological walking cycle...');

%% 6. REAL-TIME HARDWARE CONTROL LOOP
for i = 1:N
    loop_start = tic; 
    
    % 1. Compute Control Actions (Pure Math Space)
    action_R = ctrl_R.computeAction([], ref_pos_R(:, i));
    action_L = ctrl_L.computeAction([], ref_pos_L(:, i));
    
    % 2. Map Actions to Hardware Space
    hw_cmd_R = (action_R .* hw_params.DIRECTIONS(1:2)') + hw_params.OFFSETS(1:2)';
    hw_cmd_L = (action_L .* hw_params.DIRECTIONS(3:4)') + hw_params.OFFSETS(3:4)';
    
    % 3. Send all 4 commands
    hw_interface.writePosition(hw_params.DXL_IDS, [hw_cmd_R; hw_cmd_L]);
    
    % 4. Read Hardware and Map Back to Math Space
    act_angles_hw = zeros(4,1);
    for m = 1:4
        act_angles_hw(m) = hw_interface.readPosition(hw_params.DXL_IDS(m));
    end
    
    act_q_R = (act_angles_hw(1:2) - hw_params.OFFSETS(1:2)') ./ hw_params.DIRECTIONS(1:2)';
    act_q_L = (act_angles_hw(3:4) - hw_params.OFFSETS(3:4)') ./ hw_params.DIRECTIONS(3:4)';
    
    act_pos_3d_R = kinematics.forward_kinematics(act_q_R, params);
    act_pos_3d_L = kinematics.forward_kinematics(act_q_L, params);
    
    % 5. Log Data
    actual_pos_R_log(:, i) = act_pos_3d_R(1:2);
    actual_pos_L_log(:, i) = act_pos_3d_L(1:2);
    
    % 6. Pacing constraint
    elapsed_time = toc(loop_start);
    if elapsed_time < Ts
        pause(Ts - elapsed_time);
    end
end

disp('Walking complete. Cleaning up...');
hw_interface.cleanup();

%% 7. Plot Synchronized Biological Tracking
figure('Name', 'Dual Leg Bio-Synchronization', 'Color', 'w', 'Position', [100, 100, 800, 400]);

subplot(1,2,1); hold on; grid on; axis equal;
plot(ref_pos_R(1,:), ref_pos_R(2,:), 'r--', 'LineWidth', 2, 'DisplayName', 'Fennec Target');
plot(actual_pos_R_log(1,:), actual_pos_R_log(2,:), 'b-', 'LineWidth', 1.5, 'DisplayName', 'Actual');
title('Right Leg Path'); xlabel('X (mm)'); ylabel('Y (mm)'); legend;

subplot(1,2,2); hold on; grid on; axis equal;
plot(ref_pos_L(1,:), ref_pos_L(2,:), 'r--', 'LineWidth', 2, 'DisplayName', 'Fennec Target');
plot(actual_pos_L_log(1,:), actual_pos_L_log(2,:), 'b-', 'LineWidth', 1.5, 'DisplayName', 'Actual');
title('Left Leg Path'); xlabel('X (mm)'); ylabel('Y (mm)'); legend;

%% =========================================================
%% LOCAL HELPER FUNCTIONS
%% =========================================================
function [ref_x, ref_y] = generate_animal_trajectory(t_c, T_cycle, Xc, Yc, A, B, csv_file)
    % Reads the biological data, normalizes it, and maps it to the robot's physical workspace.
    
    data = readtable(csv_file);
    x_raw = data.x_px;
    z_raw = data.z_px;

    % 1. Normalize biological data between 0.0 and 1.0
    x_min = min(x_raw);
    x_max = max(x_raw);
    x_norm = (x_raw - x_min) / (x_max - x_min);

    z_min = min(z_raw);
    z_max = max(z_raw);
    if z_max == z_min
        z_norm = zeros(size(z_raw));
    else
        z_norm = (z_raw - z_min) / (z_max - z_min);
    end

    % 2. Map normalized data directly onto the robot's mechanical limits
    % X axis: Maps 0->1 to (Xc - A) -> (Xc + A)
    x_mapped = (Xc - A) + x_norm * (2 * A);

    % Y axis: Maps 0->1 to Ground (Yc - B) -> Peak (Yc + B)
    y_mapped = (Yc - B) + z_norm * (2 * B);

    % 3. Interpolate the discrete CSV points across the continuous real-time array
    % The CSV represents exactly one full cycle from time 0 to T_cycle
    t_csv = linspace(0, T_cycle, length(x_mapped))';
    
    % Use 'pchip' interpolation to preserve the smooth biological curves 
    % without introducing mathematical ringing/overshoot
    ref_x = interp1(t_csv, x_mapped, t_c, 'pchip', 'extrap');
    ref_y = interp1(t_csv, y_mapped, t_c, 'pchip', 'extrap');
end